### ISSUE TITLE
actionName is not defined

### ISSUE THREAD

**Issue by arden** [MrToph/generator-eos#2]
`ardendeiMac:test arden$ npx -p yo -p generator-eos -c 'yo eos'
? Name of your module sayonecontract
? Contract Account Name saytokenteam
/Users/arden/.npm/_npx/48166/lib/node_modules/generator-eos/generators/app/templates /Users/arden/data/test/sayonecontract
events.js:167
      throw er; // Unhandled 'error' event
      ^

ReferenceError: /Users/arden/.npm/_npx/48166/lib/node_modules/generator-eos/generators/app/templates/scripts/create_actions/action.template.js:9
    7|     try {
    8|         const contract = await eos.contract(CONTRACT_ACCOUNT)
 >> 9|         await contract.<%- actionName %>(
    10|             <%- payload %>,
    11|             { authorization: `test1` },
    12|         )

actionName is not defined
    at eval (eval at compile (/Users/arden/.npm/_npx/48166/lib/node_modules/generator-eos/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:11:17)
    at returnedFn (/Users/arden/.npm/_npx/48166/lib/node_modules/generator-eos/node_modules/ejs/lib/ejs.js:653:17)
    at Object.exports.render (/Users/arden/.npm/_npx/48166/lib/node_modules/generator-eos/node_modules/ejs/lib/ejs.js:416:37)
    at render (/Users/arden/.npm/_npx/48166/lib/node_modules/generator-eos/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:14:18)
    at process (/Users/arden/.npm/_npx/48166/lib/node_modules/generator-eos/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:31:14)
    at applyProcessingFunc (/Users/arden/.npm/_npx/48166/lib/node_modules/generator-eos/node_modules/mem-fs-editor/lib/actions/copy.js:14:16)
    at EditionInterface.exports._copySingle (/Users/arden/.npm/_npx/48166/lib/node_modules/generator-eos/node_modules/mem-fs-editor/lib/actions/copy.js:64:16)
    at files.forEach.file (/Users/arden/.npm/_npx/48166/lib/node_modules/generator-eos/node_modules/mem-fs-editor/lib/actions/copy.js:51:10)
    at Array.forEach (<anonymous>)
    at EditionInterface.exports.copy (/Users/arden/.npm/_npx/48166/lib/node_modules/generator-eos/node_modules/mem-fs-editor/lib/actions/copy.js:50:9)
Emitted 'error' event at:
    at Immediate.setImmediate (/Users/arden/.npm/_npx/48166/lib/node_modules/generator-eos/node_modules/yeoman-generator/lib/index.js:406:18)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)`

**Comment by MrToph** [comment]
Thanks, working on this

**Comment by MrToph** [comment]
Should be fixed in latest release
